name: Deploy Node App

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t mohankumar7261995490/node-app .

      - name: Publish Image to Docker Hub
        run: docker push mohankumar7261995490/node-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull mohankumar7261995490/node-app:latest

      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name node-app-container mohankumar7261995490/node-app:latest
